### ISSUE TITLE
RCON - IndexError: pop from empty list

### ISSUE THREAD

**Issue by timraay** [timraay/HLLLogUtilities#1]
```py
[2022-10-20 23:56:12,573][ERROR][base_events.default_exception_handler:1744] Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...shed result=5>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...shed result=5>)>
Traceback (most recent call last):
  File "C:\Users\traay\AppData\Local\Programs\Python\Python310\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\traay\AppData\Local\Programs\Python\Python310\Lib\asyncio\proactor_events.py", line 320, in _loop_reading
    self._data_received(data, length)
  File "C:\Users\traay\AppData\Local\Programs\Python\Python310\Lib\asyncio\proactor_events.py", line 270, in _data_received
    self._protocol.data_received(data)
  File "d:\Documents\Python\Discord Bots\HLLLogUtilities\lib\protocol.py", line 33, in data_received
    waiter = self._waiters.pop(0)
IndexError: pop from empty list
```

**Comment by timraay** [comment]
Turns out this is caused by multipart responses, and has no real fix. I've increased the time it waits for additional packets from 0.5 to 1.0 seconds which has seemed to get rid of most occurrences.

Until HLL devs add something to identify the end of the packet, this'll have to do.
